# This is basic workflow

name: Deploy ECR

# Controls workflow 
on:
  # Triggers the workflow
  push:
    branches: [ master ]
  # Allows you to run this workflow manually
  workflow_dispatch:
  
# A workflow run is made up
jobs:
  # This workflow contains "build"
  build:
    # The type of runner that the job will run on
    name: Build Image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v3

      # Runs a single command
      - name: Login Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        # Declaration of AWS Secrets
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
          AWS_REGION: us-east-1
          
      - name: Build, Test, Tag and push cats image to Amazon ECR
        env: 
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: nkotak1_a2
          IMAGE_TAG: cats
          
      # Runs a set of commands
        run: |
          cd cats/
          ls -ltra
          # Build the docker image 
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # Run the container to test
          docker run -d -p 8080:80 --name naitik-clo835-lab1-cats $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # list all the containers
          docker ps
          echo " sleep 10 seconds for container to run"
          sleep 10
          # Push the docker image to ECR repository
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
      - name: Build, Test, Tag and push dogs image to Amazon ECR
        env: 
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: nkotak1_a2
          IMAGE_TAG: dogs
          
      # Runs a set of commands
        run: |
          cd dogs/
          ls -ltra
          # Build the docker image 
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # Run the container to test
          docker run -d -p 8081:80 --name naitik-clo835-lab1-dogs $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # list all the containers
          docker ps
          echo " sleep 10 seconds for container to run"
          sleep 10
          # Push the docker image to ECR repository
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  
